<style>
#red{
            position:absolute;
            margin-top:40px; 
            margin-left:10px; 
        }
        #espace{

            margin:30px; 
        }
</style>
<div class="container" >
    <P><?php $this->flash->output() ?></p>
    <form method="post" action="<?= $this->url->get("offre/ajoutoffre")?>" class="form-signin">
        <h3 class="form-signin-heading">Ajouter une offre</h3> 

        <input type="text" name="poste" class="form-control" placeholder="Poste" required autofocus>
        <br/>	
        <input type="text" name="diplome" class="form-control" placeholder="Diplome" required autofocus>
        <br/>
        <input type="text" name="duree" class="form-control" placeholder="Durée d'emploiement" required autofocus>
        <br>
        <h4>Date d'expiration de l'offre</h4>
        <div class="datepicker-container" class="section section-javascript" id="javascriptComponents">
            <div class="form-group">
                <input type="date" class="form-control date-picker" value="10/05/2017" name="expiration"data-datepicker-color="primary">
            </div>
        </div>
        
        <button class="btn btn-lg btn-primary btn-block" type="submit">Suivant</button>
    </form>
    </br></br>
    <form id="red" method="post" action="delete">

        <?php
        foreach ($tab as $value) {

            echo '<input id ="espace" type="checkbox" name="id_of[]" value=' . $value->getId_of() . '>' . '<br/>';
        }
        ?>
        <br>
        <a href=""><button type="submit" class="btn btn-danger" data-target>Supprimer-selection</button></a>
    </form>
    <table class="table table-striped table-inverse">
        <thead>
            <tr>
                <th>#</th>
                <th>POSTE</th>
                <th>DIPLOME</th>
                <th>DUREE</th>
                <th>EXPIRATIONS</th>
            </tr>
        </thead>

        <tbody>

            <?php
            foreach ($tab as $value)
                :
                ?>

                <tr>
                    <td> </td>
                    <td><?= $value->getPoste() ?></td>

                    <td><?= $value->getDiplome() ?></td>
                    <td><?= $value->getDuree() ?></td>
                    <td><?= strftime("%x", $value->getExpiration()) ?></td>
                    <td><a href=<?= "delete?id_url=" . $value->getId_of() ?> ><button type="submit" class="btn btn-danger "  data-target data-confirm="Etes-vous certain de vouloir supprimer"><span class="glyphicon glyphicon-remove"></span>Suprimer</button></a>
                    </td>



                    <td><a href=<?= "update?id_url=" . $value->getId_of() ?>><button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-edit">Modifier</button></a></td>

                </tr>

            <?php endforeach; ?>
        </tbody>
    </table>
</div>
