<div class="container">
   <!-- Page Heading -->
    <h1 class="my-4">Bienvenue sur BworkSpace -
        <small>Les Jobs</small>
    </h1>
    <p>
        <button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#bof" aria-expanded="false" aria-controls="collapseExample">
            + Domaines
        </button>
    </p>
    <div class="collapse" id="bof">

        <input type="checkbox" id="" name="" Value="Programmation"> Programmation
        </br>		
        <input type="checkbox" id="" name="" Value="Commerciale" checked> Commerciale
        </br></br>
        <button class="btn btn-primary" type="button">Trier</button>
        </br>
    </div>
    </br>

    <div class="container marketing">

        <style>
            .img-circle{border-radius:50%}hr{margin-top:20px;margin-bottom:20px;border:0;border-top:1px solid #eee}
        </style>

        <!-- Three columns of text below the carousel -->
        <div class="row">

            <div class="col-lg-3 col-sm-6">
                <img class="img-circle" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" width="140" height="140">
                <h3>Poste</h3>
                <h4>Diplome requis</h4>
                <p>La durée</p>
                <p><a class="btn btn-primary" href="#" role="button">Voir details &raquo;</a></p>
            </div><!-- /.col-lg-4 -->  
            <div class="col-lg-3 col-sm-6">
                <img class="img-circle" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" width="140" height="140">
                <h3>Poste</h3>
                <h4>Diplome requis</h4>
                <p>La durée</p>
                <p><a class="btn btn-primary" href="#" role="button">Voir details &raquo;</a></p>
            </div><!-- /.col-lg-4 -->  
            <div class="col-lg-3 col-sm-6">
                <img class="img-circle" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" width="140" height="140">
                <h3>Poste</h3>
                <h4>Diplome requis</h4>
                <p>La durée</p>
                <p><a class="btn btn-primary" href="#" role="button">Voir details &raquo;</a></p>
            </div><!-- /.col-lg-4 -->  
            <div class="col-lg-3 col-sm-6">
                <img class="img-circle" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" width="140" height="140">
                <h3>Poste</h3>
                <h4>Diplome requis</h4>
                <p>La durée</p>
                <p><a class="btn btn-primary" href="#" role="button">Voir details &raquo;</a></p>
            </div><!-- /.col-lg-4 -->  
            <div class="col-lg-3 col-sm-6">
                <img class="img-circle" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" width="140" height="140">
                <h3>Poste</h3>
                <h4>Diplome requis</h4>
                <p>La durée</p>
                <p><a class="btn btn-primary" href="#" role="button">Voir details &raquo;</a></p>
            </div><!-- /.col-lg-4 -->  
            <div class="col-lg-3 col-sm-6">
                <img class="img-circle" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" width="140" height="140">
                <h3>Poste</h3>
                <h4>Diplome requis</h4>
                <p>La durée</p>
                <p><a class="btn btn-primary" href="#" role="button">Voir details &raquo;</a></p>
            </div><!-- /.col-lg-4 -->  
            <div class="col-lg-3 col-sm-6">
                <img class="img-circle" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" width="140" height="140">
                <h3>Poste</h3>
                <h4>Diplome requis</h4>
                <p>La durée</p>
                <p><a class="btn btn-primary" href="#" role="button">Voir details &raquo;</a></p>
            </div><!-- /.col-lg-4 -->
        </div>
    </div>
</div>
