<style>

    body {

        text-align:center;
        padding-bottom: 40px;
        background-image:url('img/th210NKBIO.jpg');
        background-repeat: no-repeat;
        background-size: cover;  


    }

    .form-signin {
        max-width: 330px;
        padding: 15px;
        margin: 0 auto;
    }
    .form-signin .form-signin-heading,
    .form-signin .checkbox {
        margin-bottom: 10px;
    }
    .form-signin .checkbox {
        font-weight: normal;
    }
    .form-signin .form-control {
        position: relative;
        height: auto;
        -webkit-box-sizing: border-box;
        -moz-box-sizing: border-box;
        box-sizing: border-box;
        padding: 10px;
        font-size: 16px;
    }
    .form-signin .form-control:focus {
        z-index: 2;
    }
    .form-signin input[type="email"] {
        margin-bottom: -1px;
        border-bottom-right-radius: 0;
        border-bottom-left-radius: 0;
    }
    .form-signin input[type="password"] {
        margin-bottom: 10px;
        border-top-left-radius: 0;
        border-top-right-radius: 0;
    }



</style>


<div class="container">
    <P><?php $this->flashSession->output() ?></p>
        <form class="form-signin" method="post" action="<?= $this->url->get("entreprise/inscriptionEnt")?>">
        <h3 class="form-signin-heading">Inscription Entreprise</h3> 

        <input type="text" class="form-control"  name="nom" placeholder="Nom de l'entreprise" required autofocus>
        <br/>	
        <hr/>
        <H5>Secteur d'activite</H5>      

        <table>
            <?php
            foreach ($tab as $value):
                ?>    

                <td>


                    <input type="checkbox" name="categori[]" value="<?=$value->getId_cat()?>">
                <th><?=$value->getNom()?></th>
                </td>

                <?php
            endforeach;
            ?>   
        </table>

        <br/>   	
        <H5>Departement</H5>      
        <Select name="region">
            <option>Atlantique</option>
            <option>Litoral</option>
            <option>Borgou</option>
            <option>Alibori</option>
            <option>Attacora</option>
            <option>Donga</option>
            <option>Mono</option>
            <option>Couffo</option>
            <option>Collines</option>
            <option>Zou</option>
            <option>Oueme</option>
            <option>Plateau</option>
        </Select>
        <br/><br/>
        <input type="Email" class="form-control" name="mail" placeholder="Adresse E-mail" required autofocus>

        <input type="text" class="form-control" name="adresse" placeholder="Adresse Siege" required autofocus>
        <input type="text" class="form-control"  name="telephone" placeholder="Numero de telephone" required autofocus>
        <br/>
        <input type="password" id="inputPassword" class="form-control" name="password" placeholder="Mot de passe" required>
        <input type="password" id="inputPassword" class="form-control"  name="cpassword" placeholder="Confirmer le mot de passe" required>

        <br/>

        <button class="btn btn-lg btn-primary btn-block" type="submit">Suivant</button>
    </form>

</div>