<link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />
<?php
    if ($this->session->has('id_ent')|| isset($_GET["id"]))  {
        
        foreach ($tab as $value):
        ?>

<body class="landing-page sidebar-collapse">
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg bg-info fixed-top navbar-transparent " color-on-scroll="400">
        <div class="container">
            <div class="dropdown button-dropdown">BworkSpace
                <a href="#pablo" class="dropdown-toggle" id="navbarDropdown" data-toggle="dropdown">
                    <span class="button-bar"></span>
                    <span class="button-bar"></span>
                    <span class="button-bar"></span>
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-header">Parametres</a>
                    <?php if ($this->session->has('id_ent')):  ?>
                    <a class="dropdown-item" href="<?= $this->url->get("entreprise/updateEnt")?>">Mise à jour du compte</a>
                    <?php endif; ?>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="<?= $value->getSiteweb()?>">Aller au Site web</a>
                    <div class="dropdown-divider"></div>
                    
                </div>
            </div>
            <div class="navbar-translate">

                <button class="navbar-toggler navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-bar bar1"></span>
                    <span class="navbar-toggler-bar bar2"></span>
                    <span class="navbar-toggler-bar bar3"></span>
                </button>
            </div>
            <?php if ($this->session->has('id_ent')):  ?>
            <div class="collapse navbar-collapse justify-content-end" id="navigation" data-nav-image="../assets/img/blurred-image-1.jpg">
                <ul class="navbar-nav">


                    <li class="nav-item">
                        <a class="nav-link" rel="tooltip" title="Voir liste des offres soumissent" data-placement="bottom" href="<?= $this->url->get("offre/delete")?>" target="_blank">
                            <p class="">Nos Offres d'emplois</p>
                        </a>
                    </li>
                     <li class="nav-item">
                        <a class="nav-link" rel="tooltip" title="Voir liste des offres soumissent" data-placement="bottom" href="<?= $this->url->get("job/delete")?>" target="_blank">
                            <p class="">Nos Jobs De Vacance</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" rel="tooltip" title="Voir liste des demandes d'emplois" data-placement="bottom" href="" target="_blank">
                            <p class="">Demandes d'emplois</p>
                        </a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="<?= $this->url->get("entreprise/deconnection")?>">Deconnexion</a>
                    </li>

                </ul>
            </div>
            <?php endif; ?>
        </div>
    </nav>
    <!-- End Navbar -->
    <div class="wrapper">
        <div class="page-header page-header-small">
            <?php //var_dump($this->uploadEnt.$value->getLogo());?>
            <div class="page-header-image" data-parallax="true" style='background-image: url("<?="http://".$_SERVER['SERVER_NAME'].$this->url->get($value->getLogo())?>");'>
            </div>
            <div class="container">
                <div class="content-center">
                    <h1 class="title"><?=$value->getNom()?></h1>
                    <div class="text-center">

                        <style>
                            .img-circle{border-radius:50%}hr{margin-top:20px;margin-bottom:20px;border:0;border-top:1px solid #eee}
                        </style>

                        <img class="img-circle" src="<?=$this->url->get($value->getLogo())?>" alt="Generic placeholder image" width="140" height="140">
                        <h6 class="title"><?=$value->getAdresse()?></h6>
                        <h6 class="title"><?=$value->getTelephone()?></h6>
                        <h6 class="title"><?=$value->getRegion()?></h6>

                    </div>
                </div>
            </div>
        </div>
        <div class="section section-about-us">
            <div class="container">
                <div class="row">
                    <div class="col-md-8 ml-auto mr-auto text-center">
                        <h2 class="title">Qui sommes nous?</h2>
                        <h5 class="description"><?=$value->getDescription()?></h5>
                    </div>
                </div>
                <div class="separator separator-primary"></div>
                <div class="section-story-overview">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="image-container image-left" style="background-image: url('../assets/img/login.jpg')">
                                <!-- First image on the left side -->

                            </div>
                            <!-- Second image on the left side of the article -->
                            <div class="image-container" style="background-image: url('../assets/img/bg3.jpg')"></div>
                        </div>
                        <div class="col-md-5">
                            <!-- First image on the right side, above the article -->
                            <div class="image-container image-right" style="background-image: url('../assets/img/bg1.jpg')"></div>
                            <h3>Historique</h3>
                            <p>The Arctic Ocean freezes every winter and much of the sea-ice then thaws every summer, and that process will continue whatever happens with climate change. Even if the Arctic continues to be one of the fastest-warming regions of the world, it will always be plunged into bitterly cold polar dark every winter. And year-by-year, for all kinds of natural reasons, there’s huge variety of the state of the ice.
                            </p>
                            <p>
                                For a start, it does not automatically follow that a record amount of ice will melt this summer. More important for determining the size of the annual thaw is the state of the weather as the midnight sun approaches and temperatures rise. But over the more than 30 years of satellite records, scientists have observed a clear pattern of decline, decade-by-decade.
                            </p>
                            <p>The Arctic Ocean freezes every winter and much of the sea-ice then thaws every summer, and that process will continue whatever happens with climate change. Even if the Arctic continues to be one of the fastest-warming regions of the world, it will always be plunged into bitterly cold polar dark every winter. And year-by-year, for all kinds of natural reasons, there’s huge variety of the state of the ice.
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>



        <footer class="footer footer-default">
            <div class="container">
                <div class="copyright">
                    &copy;
                    <script>
                        document.write(new Date().getFullYear())
                    </script>, Designed by Kyrigami

                </div>
            </div>
        </footer>
    </div>
</body>
<!--   Core JS Files   -->
<script src="../assets/js/core/jquery.3.2.1.min.js" type="text/javascript"></script>
<script src="../assets/js/core/popper.min.js" type="text/javascript"></script>
<script src="../assets/js/core/bootstrap.min.js" type="text/javascript"></script>
<!--  Plugin for Switches, full documentation here: http://www.jque.re/plugins/version3/bootstrap.switch/ -->
<script src="../assets/js/plugins/bootstrap-switch.js"></script>
<!--  Plugin for the Sliders, full documentation here: http://refreshless.com/nouislider/ -->
<script src="../assets/js/plugins/nouislider.min.js" type="text/javascript"></script>
<!--  Plugin for the DatePicker, full documentation here: https://github.com/uxsolutions/bootstrap-datepicker -->
<script src="../assets/js/plugins/bootstrap-datepicker.js" type="text/javascript"></script>
<!-- Control Center for Now Ui Kit: parallax effects, scripts for the example pages etc -->
<script src="../assets/js/now-ui-kit.js?v=1.1.0" type="text/javascript"></script>

</html>
<?php
    endforeach;
    
    }else{
        $this->flash->error("Connecter vous");
                return $this->response->redirect($this->url->getBaseUri() . "index", true);
    }
        
    
        ?>