<style>
    body {
        
        text-align:center;
        padding-top: 100px;
        padding-bottom: 40px;
        background-image:url('img/th210NKBIO.jpg');
        background-repeat: no-repeat;
        background-size: cover;  
    }

    .form-signin {
        max-width: 330px;
        padding: 15px;
        margin: 0 auto;
    }
    .form-signin .form-signin-heading,
    .form-signin .checkbox {
        margin-bottom: 10px;
    }
    .form-signin .checkbox {
        font-weight: normal;
    }
    .form-signin .form-control {
        position: relative;
        height: auto;
        -webkit-box-sizing: border-box;
        -moz-box-sizing: border-box;
        box-sizing: border-box;
        padding: 10px;
        font-size: 16px;
    }
    .form-signin .form-control:focus {
        z-index: 2;
    }
    .form-signin input[type="email"] {
        margin-bottom: -1px;
        border-bottom-right-radius: 0;
        border-bottom-left-radius: 0;
    }
    .form-signin input[type="password"] {
        margin-bottom: 10px;
        border-top-left-radius: 0;
        border-top-right-radius: 0;
    }
</style>

<div class="container">
    <P><?php $this->flashSession->output() ?></p>
    <?php foreach ($tab1 as $value1): ?>

    <form class="form-signin" method="post" action="<?= $this->url->get("entreprise/updateEnt")?>" enctype="multipart/form-data">
        <h2 class="form-signin-heading">Mise à jour</h2>
        
        <input type="Email" id="email" class="form-control" name="mail" value=<?=$value1->getMail()?>  required>
        <input type="password" id="inputPassword" class="form-control" name="password" placeholder="Entrez votre mot de passe Pour verification" required>

        <input type="file" id="file" class="form-control" name="photo" placeholder="logo" required>
        <input type="text" id="text" class="form-control" name="nom" value=<?=$value1->getNom()?> required>

        <br/>       <h2 class="form-signin-heading">Secteur d'activité</h2>
           

        <table>
            <?php
            foreach ($tab as $value):
                ?>    

                <td>


                    <input type="checkbox" name="categori[]" value="<?=$value->getId_cat()?>">
                <th><?=$value->getNom()?></th>
                </td>

                <?php
            endforeach;
            ?>   
        </table>
        

        <br/>  
<H5>Departement</H5>      
        <Select name="region">
            <option>Atlantique</option>
            <option>Litoral</option>
            <option>Borgou</option>
            <option>Alibori</option>
            <option>Attacora</option>
            <option>Donga</option>
            <option>Mono</option>
            <option>Couffo</option>
            <option>Collines</option>
            <option>Zou</option>
            <option>Oueme</option>
            <option>Plateau</option>
        </Select>
        <br/><br/>        
        <input type="text" id="inputEmail" class="form-control" name="adresse" value=<?=$value1->getAdresse()?>autofocus>
        <input type="text" id="siteweb" class="form-control" name="siteweb" placeholder="lien vers le site de l'entreprise">
        <input type="text" class="form-control" name="telephone"value=<?=$value1->getTelephone()?>>
        <textarea type="" id="description" class="form-control" name="description" ></textarea>
        <br/>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Modifier</button>
    </form>
    <?php endforeach; ?>
</div>