<!-- Page Content -->
<div class="container">

    <!-- Page Heading -->
    <h1 class="my-4">Bienvenue sur BworkSpace -
        <small>Les Entreprises</small>
    </h1>
    
    <P><?php $this->flash->output() ?></p>

    <p>
        <button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#bof" aria-expanded="false" aria-controls="collapseExample">
            + Catégories
        </button>
    </p>
    <div class="collapse" id="bof">

        <input type="checkbox" id="" name="" Value="Programmation"> Programmation
        <br>
        <input type="checkbox" id="" name="" Value="Commerciale" checked> Commerciale
        <br>
        <br>
        <button class="btn btn-primary" type="button">Trier</button>
        <br>
    </div>
    <br>

    <div class="row">
        <div class="col-lg-3 col-sm-6 portfolio-item">
            <div class="card h-100">
                <a href="#"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
                <div class="card-body">
                    <h4 class="card-title">
                        <a href="#">Entreprise 1</a>
                    </h4>
                    <p class="card-text">bla bala bala</p>
                    <a class="btn btn-primary" href="#">Voir details</a>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-sm-6 portfolio-item">
            <div class="card h-100">
                <a href="#"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
                <div class="card-body">
                    <h4 class="card-title">
                        <a href="#">Entreprise 2</a>
                    </h4>
                    <p class="card-text">blabla</p>
                    <a class="btn btn-primary" href="#">Voir details</a>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-sm-6 portfolio-item">
            <div class="card h-100">
                <a href="#"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
                <div class="card-body">
                    <h4 class="card-title">
                        <a href="#">Entreprise 3</a>
                    </h4>
                    <p class="card-text">bla blab bla</p>
                    <a class="btn btn-primary" href="#">Voir details</a>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-sm-6 portfolio-item">
            <div class="card h-100">
                <a href="#"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
                <div class="card-body">
                    <h4 class="card-title">
                        <a href="#">Entreprise 4</a>
                    </h4>
                    <p class="card-text">bla bla bla</p>
                    <a class="btn btn-primary" href="#">Voir details</a>
                </div>
            </div>
        </div>
        <br/>
        <div class="col-lg-3 col-sm-6 portfolio-item">
            <div class="card h-100">
                <a href="#"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
                <div class="card-body">
                    <h4 class="card-title">
                        <a href="#">Entreprise 5</a>
                    </h4>
                    <p class="card-text">bla bal bla</p>
                    <a class="btn btn-primary" href="#">Voir details</a>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-sm-6 portfolio-item">
            <div class="card h-100">
                <a href="#"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
                <div class="card-body">
                    <h4 class="card-title">
                        <a href="#">Entreprise 6</a>
                    </h4>
                    <p class="card-text">bla bla bla</p>
                    <a class="btn btn-primary" href="#">Voir details</a>
                </div>
            </div>
        </div>
    </div>
</div>
