<style>

    body {

        padding-bottom: 40px;
        color:white;
        text-align:center;
        padding-bottom: 40px;
        background-image:url('img/th210NKBIO.jpg');
        background-repeat: no-repeat;
        background-size: cover;  

    }

    .form-signin {
        max-width: 330px;
        padding: 15px;
        margin: 0 auto;
    }
    .form-signin .form-signin-heading,
    .form-signin .checkbox {
        margin-bottom: 10px;
    }
    .form-signin .checkbox {
        font-weight: normal;
    }
    .form-signin .form-control {
        position: relative;
        height: auto;
        -webkit-box-sizing: border-box;
        -moz-box-sizing: border-box;
        box-sizing: border-box;
        padding: 10px;
        font-size: 16px;
    }
    .form-signin .form-control:focus {
        z-index: 2;
    }
    .form-signin input[type="email"] {
        margin-bottom: -1px;
        border-bottom-right-radius: 0;
        border-bottom-left-radius: 0;
    }
    .form-signin input[type="password"] {
        margin-bottom: 10px;
        border-top-left-radius: 0;
        border-top-right-radius: 0;
    }

</style>


<div class="container">

    <form class="form-signin" action="" method="post">
        <h3 class="form-signin-heading">Inscription Particulier</h3>

        <input type="text" id="" class="form-control" placeholder="Nom" required autofocus>
        <input type="text" id="" class="form-control" placeholder="Prenom" required autofocus>
        <br/>
        <input type="email" id="" class="form-control" placeholder="Email" required autofocus>
        <input type="number" id="" class="form-control" placeholder="Telephone" required autofocus>
        <br/>
        <H5>Votre Region</H5>      
        <Select name="Departement">
            <option>Atlantique</option>
            <option>Litoral</option>
            <option>Borgou</option>
            <option>Alibori</option>
            <option>Attacora</option>
            <option>Donga</option>
            <option>Mono</option>
            <option>Couffo</option>
            <option>Collines</option>
            <option>Zou</option>
            <option>Oueme</option>
            <option>Plateau</option>
        </Select>
        <br/>
        <br/>
        <input type="password" id="inputPassword" class="form-control" placeholder="Mot de passe" required>
        <input type="password" id="inputPassword" class="form-control" placeholder="Confirmer mot de passe" required>
        <br/>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Suivant</button>
    </form>

</div>