<style>
    body {
        color:white;
        text-align:center;
        padding-top: 100px;
        padding-bottom: 40px;
        background-image:url('img/th210NKBIO.jpg');
        background-repeat: no-repeat;
        background-size: cover;  
    }

    .form-signin {
        max-width: 330px;
        padding: 15px;
        margin: 0 auto;
    }
    .form-signin .form-signin-heading,
    .form-signin .checkbox {
        margin-bottom: 10px;
    }
    .form-signin .checkbox {
        font-weight: normal;
    }
    .form-signin .form-control {
        position: relative;
        height: auto;
        -webkit-box-sizing: border-box;
        -moz-box-sizing: border-box;
        box-sizing: border-box;
        padding: 10px;
        font-size: 16px;
    }
    .form-signin .form-control:focus {
        z-index: 2;
    }
    .form-signin input[type="email"] {
        margin-bottom: -1px;
        border-bottom-right-radius: 0;
        border-bottom-left-radius: 0;
    }
    .form-signin input[type="password"] {
        margin-bottom: 10px;
        border-top-left-radius: 0;
        border-top-right-radius: 0;
    }
</style>

<div class="container">
    <form class="form-signin" action="  <?php
    if ($this->request->isPost()) {
        $type = $this->request->getPost("type");


        if ($type == "Entreprise") {
            ?>

                  <?= $this->url->get("entreprise/login") ?>
              <?php } elseif ($type == "Particulier") { ?>
                  <?= $this->url->get("particulier/login") ?>
              <?php } elseif ($type == "Prestataire") { ?>
                  <?= $this->url->get("prestataire/login") ?> 

                  <?php
              }
          } else {
              ?>
              <?= $this->url->get("index") ?>
          <?php } ?>" method="post">
        <h2 class="form-signin-heading">

        </h2>
        <label for="inputEmail" class="sr-only">Mail</label>
        <input type="email" id="inputEmail" class="form-control"  name="mail" placeholder="Email address" required autofocus>
        <br/>
        <label for="inputPassword" class="sr-only">Mot de Passe</label>
        <input type="password" id="inputPassword" name="password" class="form-control" placeholder="Password" required>
        <div class="checkbox">
            <label>
                <input type="checkbox" value="remember-me"> Remember me
            </label>
        </div>
        <button class="btn btn-lg btn-primary btn-block" type="submit">se connecter</button>
        <p><a class="btn btn-default" href=" <?php
              if ($this->request->isPost()) {
                  $type = ($_POST['type']);


                  if ($type == "Entreprise") {
                      ?>
                      <?= $this->url->get("entreprise/inscriptionEnt") ?>
                  <?php } elseif ($type == "Particulier") { ?>
                      <?= $this->url->get("particulier/inscriptionPers") ?>
                  <?php } elseif ($type == "Prestataire") { ?>
                      <?= $this->url->get("prestataire/inscriptionPrest") ?>
                      <?php
                  }
              }
              ?> " >Je veux m'inscrire
            </a></p>
    </form>
</div> <!-- /container -->
