<style>
    body {
        color:white;
        text-align:center;
        padding-top: 100px;
        padding-bottom: 40px;
        background-image:url("<?= $this->url->get("img/th210NKBIO.jpg")?>");
        background-repeat: no-repeat;
        background-size: cover;  
    }
</style>

<div class="container">
    <form class="form-signin" action="" method="post">
        <h2 class="form-signin-heading">
            <?php
            $type = ($_POST['type']);
            ?>
        </h2>
        <label for="inputEmail" class="sr-only">Nom d'utilisateur</label>
        <input type="email" id="inputEmail" class="form-control" placeholder="Email address" required autofocus>
        <br/>
        <label for="inputPassword" class="sr-only">Mot de Passe</label>
        <input type="password" id="inputPassword" class="form-control" placeholder="Password" required>
        <div class="checkbox">
            <label>
                <input type="checkbox" value="remember-me"> Remember me
            </label>
        </div>
        <button class="btn btn-lg btn-primary btn-block" type="submit"><a href="  <?php
            $type = ($_POST['type']);

            if ($type == "Entreprise") {
                ?>

                                                                              <?= $this->url->get("entreprise/profil") ?>
                                                                          <?php } elseif ($type == "Particulier") { ?>
                                                                              <?= $this->url->get("particulier/profil") ?>
                                                                          <?php } elseif ($type == "Prestataire") { ?>
                                                                              <?= $this->url->get("prestataire/profil") ?> 
                                                                          <?php } ?>">Se connecter</a></button>
        <p><a class="btn btn-default" href=" <?php
              $type = ($_POST['type']);


              if ($type == "Entreprise") {
                  ?>
                  <?= $this->url->get("entreprise/inscriptionEnt") ?>
              <?php } elseif ($type == "Particulier") { ?>
                  <?= $this->url->get("particulier/inscriptionPers") ?>
              <?php } elseif ($type == "Prestataire") { ?>
                  <?= $this->url->get("prestataire/inscriptionPrest") ?>
              <?php }
              ?> " >Je veux m'inscrire
            </a></p>
    </form>
</div> <!-- /container -->
