<style>
    .marketing .col-lg-3 {
        margin-bottom: 20px;
        text-align: center;
    }
    .marketing h2 {
        font-weight: normal;
    }
    .marketing .col-lg-3 p {
        margin-right: 10px;
        margin-left: 10px;
    }
    @-ms-viewport     { width: device-width; }
    @-o-viewport      { width: device-width; }
    @viewport         { width: device-width; }
</style>

<div class="container">

    <!-- Page Heading -->
    <h1 class="my-4">Bienvenue sur BworkSpace -
        <small>Les Particuliers</small>
    </h1>

    </br>

    <div class="container marketing">

        <style>
            .img-circle{border-radius:50%}hr{margin-top:20px;margin-bottom:20px;border:0;border-top:1px solid #eee}
            .row h2{
                color: black;
            }
        </style>

        <!-- Three columns of text below the carousel -->
        <div class="row">
            <?php foreach ($page->items as $item): ?>
                <div class="col-lg-3 col-sm-6">
                    <img class="img-circle" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" width="140" height="140">
                    <h2><?= $item->getNom() . " " . $item->getPrenom() ?></h2> 
                    <p><?= $item->getProfession() ?></p>
                    <p><a class="btn btn-primary" data-toggle="modal" data-target="#Modal<?=$item->getId_part() ?>" role="button" href="#">Voir details</a></p>
                    <!-- Modal -->
                    <div class="modal fade" id="Modal<?= $item->getId_part()?>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLabel"><?= $item->getNom() . " " . $item->getPrenom() ?></h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    <p><?= $item->getProfession() ?></p>
                                    <p><?= $item->getTelephone() ?></p>
                                    <p><?= $item->getMail() ?></p>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                </div>
                            </div>
                        </div>
                    </div>  
                </div><!-- /.col-lg-4 -->

            <?php endforeach; ?>      
            <br><br>
        </div>
        <div class="btn-group">
            <p><a class="btn btn-primary btn-simple btn-round" href="<?= $this->url->getBaseUri() . "particulier/particulier" ?>">First</a></p>
            <p><a class="btn btn-primary btn-simple btn-round" href="<?= $this->url->getBaseUri() . "particulier/particulier" . "?page=" . $page->before ?>">Previous</a></p>
            <p><a class="btn btn-primary btn-simple btn-round" href="<?= $this->url->getBaseUri() . "particulier/particulier" . "?page=" . $page->next ?>">Next</a></p>
            <p><a class="btn btn-primary btn-simple btn-round" href="<?= $this->url->getBaseUri() . "particulier/particulier" . "?page=" . $page->last ?>">Last</a></p>
        </div>
        <br>         
        <!-- /.row -->
    </div>
</div>
