<nav class="navbar navbar-expand-lg bg-info fixed-top navbar-transparent " color-on-scroll="400">
    <div class="container">
        <div class="dropdown button-dropdown">BworkSpace
            <a href="#pablo" class="dropdown-toggle" id="navbarDropdown" data-toggle="dropdown">
                <span class="button-bar"></span>
                <span class="button-bar"></span>
                <span class="button-bar"></span>
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-header">Parametres</a>
                <a class="dropdown-item" href="<?= $this->url->get("particulier/updatePart") ?>">Mise à jour du profil</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">suprimer le compte</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="<?= $this->url->get("particulier/deconnection") ?>">Deconnexion</a>
            </div>
        </div>
        <div class="navbar-translate">

            <button class="navbar-toggler navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-bar bar1"></span>
                <span class="navbar-toggler-bar bar2"></span>
                <span class="navbar-toggler-bar bar3"></span>
            </button>
        </div>

    </div>
</nav>
<!-- End Navbar -->
<div class="wrapper">
    <div class="page-header page-header-small" filter-color="blue">
        <div class="page-header-image" data-parallax="true" style="background-image: url(<?= $this->url->get("public/img/bg5.jpg") ?>);">
        </div>
        <div class="container">
            <div class="content-center">
                <div class="photo-container">
                    <img src="<?= $this->url->get("public/img/ryan.jpg") ?>" class="rounded-circle" width="200" height="200" alt="">
                </div>
                <?php
                foreach ($tab as $value) {
                    ?>
                <h3><?= $value->getNom() . " " . $value->getPrenom() ?></h3>
                <?php } ?>
                <p class="category">Métier</p>

            </div>
        </div>
    </div>
    <div class="container">
        <div class="content">
            <style>
                .content {
                    max-width: 450px;
                    margin: auto;
                }
                .social-description{
                    display: inline-block;
                    margin: 40px;
                }
                .social-description h2 {
                    text-align: center;
                }

            </style>
            <div class="social-description">
                <h2>26</h2>
                <p>Offres</p>
            </div>
            <div class="social-description">
                <h2>3</h2>
                <p>Demandes</p>
            </div>
            <div class="social-description">
                <h2>1</h2>
                <p>employés</p>
            </div>
        </div>
        <div class="section">
            <style>
                    .section .button-container a{ 
                        display: inline-block;
                        align-content: center; 
                    }
                </style>
            <div class="button-container">
                
                <a href="#button" class="btn btn-primary btn-simple btn-round">Voir Cv</a>
            </div>

            <h3 class="title">A Propos de ma structure</h3>
            <h5 class="description">An artist of considerable range, Ryan — the name taken by Melbourne-raised, Brooklyn-based Nick Murphy — writes, performs and records all of his own music, giving it a warm, intimate feel with a solid groove structure. An artist of considerable range.</h5>
            <div class="row">
                <div class="col-md-6 ml-auto mr-auto">
                    <h4 class="title text-center">Apercu de ma structure</h4>
                    <div class="nav-align-center">
                        <ul class="nav nav-pills nav-pills-info" role="tablist">
                            <li class="nav-item">
                                <a class="nav-link" data-toggle="tab" href="#profile" role="tablist">
                                    <i class="now-ui-icons design_image"></i>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link active" data-toggle="tab" href="#home" role="tablist">
                                    <i class="now-ui-icons location_world"></i>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" data-toggle="tab" href="#messages" role="tablist">
                                    <i class="now-ui-icons sport_user-run"></i>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
                <!-- Tab panes -->
                <div class="tab-content gallery">
                    <div class="tab-pane active" id="home" role="tabpanel">
                        <div class="col-md-10 ml-auto mr-auto">
                            <div class="row collections">
                                <div class="col-md-6">
                                    <img src="<?= $this->url->get("public/img/bg1.jpg")?>" alt="" class="img-raised">
                                    <img src="<?= $this->url->get("public/img/bg3.jpg")?>" alt="" class="img-raised">
                                </div>
                                <div class="col-md-6">
                                    <img src="<?= $this->url->get("public/img/bg8.jpg")?>" alt="" class="img-raised">
                                    <img src="<?= $this->url->get("public/img/bg7.jpg")?>" alt="" class="img-raised">
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="tab-pane" id="profile" role="tabpanel">
                        <div class="col-md-10 ml-auto mr-auto">
                            <div class="row collections">
                                <div class="col-md-6">
                                    <img src="<?= $this->url->get("public/img/bg6.jpg")?>" class="img-raised">
                                    <img src="<?= $this->url->get("public/img/bg11.jpg")?>" alt="" class="img-raised">
                                </div>
                                <div class="col-md-6">
                                    <img src="<?= $this->url->get("public/img/bg7.jpg")?>" alt="" class="img-raised">
                                    <img src="<?= $this->url->get("public/img/bg8.jpg")?>" alt="" class="img-raised">
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="tab-pane" id="messages" role="tabpanel">
                        <div class="col-md-10 ml-auto mr-auto">
                            <div class="row collections">
                                <div class="col-md-6">
                                    <img src="<?= $this->url->get("public/img/bg3.jpg")?>" alt="" class="img-raised">
                                    <img src="<?= $this->url->get("public/img/bg8.jpg")?>" alt="" class="img-raised">
                                </div>
                                <div class="col-md-6">
                                    <img src="<?= $this->url->get("public/img/bg7.jpg")?>" alt="" class="img-raised">
                                    <img src="<?= $this->url->get("public/img/bg6.jpg")?>" class="img-raised">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

