<div class="container">
    <style>
        body {
            color:white;
            text-align:center;
            padding-top: 100px;
            padding-bottom: 40px;
            background-image:url('img/th210NKBIO.jpg');
            background-repeat: no-repeat;
            background-size: cover;  
        }

        .form-signin {
            max-width: 330px;
            padding: 15px;
            margin: 0 auto;
        }
        .form-signin .form-signin-heading,
        .form-signin .checkbox {
            margin-bottom: 10px;
        }
        .form-signin .checkbox {
            font-weight: normal;
        }
        .form-signin .form-control {
            position: relative;
            height: auto;
            -webkit-box-sizing: border-box;
            -moz-box-sizing: border-box;
            box-sizing: border-box;
            padding: 10px;
            font-size: 16px;
        }
        .form-signin .form-control:focus {
            z-index: 2;
        }
        .form-signin input[type="email"] {
            margin-bottom: -1px;
            border-bottom-right-radius: 0;
            border-bottom-left-radius: 0;
        }
        .form-signin input[type="password"] {
            margin-bottom: 10px;
            border-top-left-radius: 0;
            border-top-right-radius: 0;
        }
    </style>
    <form class="form-signin">
        <h2 class="form-signin-heading">Mise à jour</h2>

        <input type="email" id="inputEmail" class="form-control" placeholder="Email address" required autofocus>

        <input type="password" id="inputPassword" class="form-control" placeholder="Password" required>

        <input type="file" id="inputEmail" class="form-control" placeholder="Photo" required autofocus>

        <input type="text" id="inputEmail" class="form-control" placeholder="Nom" required autofocus>

        <input type="text" id="inputEmail" class="form-control" placeholder="Prenom" required autofocus>

        <input type="text" id="inputEmail" class="form-control" placeholder="Niveau d'etude" required autofocus>

        <textarea type="" id="description" class="form-control" placeholder="Description de ma structure"></textarea>
        <br/>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Modifier</button>
    </form>
</div> <!-- /container -->
